### PR TITLE
[Patch]: paired coding session update

### PR DESCRIPTION
**Pull request by rediris**
Changes include:
- config variable refactoring
- header/footer refactoring
- global data variable renaming

### CODE REVIEW

**Review by jgagne — CHANGES_REQUESTED** [review]
Updates look good — except the last nav, "Affiliated Sites," doesn't display after the inclusions of the image attributes. Please advise. 🙏

**Comment by rediris** [comment]
> Updates look good — except the last nav, "Affiliated Sites," doesn't display after the inclusions of the image attributes. Please advise. 🙏

I'll take a peek!

**Comment by rediris** [comment]
> > Updates look good — except the last nav, "Affiliated Sites," doesn't display after the inclusions of the image attributes. Please advise. 🙏
> 
> I'll take a peek!

@jgagne it appears to be in the markup if you view page source, but it's not visible for some reason.

**Comment by rediris** [comment]
@jgagne fixed. It happened because I removed the temporary dev footer menu, and that CSS was hiding it.

**Pull request merged**
